name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Show dotnet info
        run: dotnet --info

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # 🔎 Diagnostics so we see your repo layout on the runner
      - name: List repo contents
        shell: pwsh
        run: |
          Write-Host "== Root =="
          Get-ChildItem -Force | Format-Table
          if (Test-Path src) {
            Write-Host "== src =="
            Get-ChildItem -Force src | Format-Table
          }
          if (Test-Path src\InvApp) {
            Write-Host "== src\InvApp =="
            Get-ChildItem -Force src\InvApp | Format-Table
          }

      # ✅ Use full path to the project file; do NOT rely on working-directory
      - name: Restore
        run: dotnet restore .\src\InvApp\InvApp.csproj

      - name: Build (Release)
        run: dotnet build .\src\InvApp\InvApp.csproj -c Release --no-restore

      # If/when you add tests, point this to your test csproj
      # - name: Test
      #   run: dotnet test .\tests\InvApp.Tests\InvApp.Tests.csproj -c Release --no-build --verbosity normal

      - name: Publish (sanity)
        run: dotnet publish .\src\InvApp\InvApp.csproj -c Release -o .\out --no-restore
