name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore src/InvApp/InvApp.csproj

      - name: Build (Release)
        run: dotnet build src/InvApp/InvApp.csproj -c Release --no-restore

      # If you add tests later, point this to your test csproj
      # - name: Test
      #   run: dotnet test tests/InvApp.Tests/InvApp.Tests.csproj -c Release --no-build --verbosity normal
