name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Show dotnet info
        run: dotnet --info

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Use the project directory explicitly so paths are never wrong
      - name: Restore
        working-directory: src/InvApp
        run: dotnet restore InvApp.csproj

      - name: Build (Release)
        working-directory: src/InvApp
        run: dotnet build InvApp.csproj -c Release --no-restore

      # If you add tests later, uncomment and point to your test csproj
      # - name: Test
      #   working-directory: tests/InvApp.Tests
      #   run: dotnet test InvApp.Tests.csproj -c Release --no-build --verbosity normal

      # Optional: ensure publish succeeds too
      - name: Publish (sanity)
        working-directory: src/InvApp
        run: dotnet publish InvApp.csproj -c Release -o out --no-restore
